export const EVENTS = Object.freeze({
  // Uploads
  UPLOAD_CREATED: "UPLOAD_CREATED",
  MULTIPLE_UPLOADS_CREATED: "MULTIPLE_UPLOADS_CREATED",
  UPLOAD_UPDATED: "UPLOAD_UPDATED",
  UPLOAD_DELETED: "UPLOAD_DELETED",

  // Users
  USER_REGISTERED: "USER_REGISTERED",
  USER_LOGIN: "USER_LOGIN",
  USER_LOGOUT: "USER_LOGOUT",

  // Roles
  ROLE_CREATED: "ROLE_CREATED",
  ROLE_UPDATED: "ROLE_UPDATED",
  ROLE_DELETED: "ROLE_DELETED",

  // Notifications
  NOTIFICATION_CREATED: "NOTIFICATION_CREATED",
  NOTIFICATION_UPDATED: "NOTIFICATION_UPDATED",
  NOTIFICATION_DELETED: "NOTIFICATION_DELETED",

  // Permissions
  PERMISSION_CREATED: "PERMISSION_CREATED",
  PERMISSION_UPDATED: "PERMISSION_UPDATED",
  PERMISSION_DELETED: "PERMISSION_DELETED",

  // Plans
  PLAN_CREATED: "PLAN_CREATED",
  PLAN_UPDATED: "PLAN_UPDATED",
  PLAN_DELETED: "PLAN_DELETED",

  // Profiles
  PROFILE_CREATED: "PROFILE_CREATED",
  PROFILE_UPDATED: "PROFILE_UPDATED",
  PROFILE_AVATAR_UPDATED: "PROFILE_AVATAR_UPDATED",
  PROFILE_PASSWORD_CHANGED: "PROFILE_PASSWORD_CHANGED",

  // Tests
  TEST_CREATED: "TEST_CREATED",
  TEST_UPDATED: "TEST_UPDATED",
  TEST_DELETED: "TEST_DELETED",
});
