export const MODULES = Object.freeze({
  AUTH: "AUTH",
  AUDIT_LOGS: "AUDIT_LOGS",
  NOTIFICATIONS: "NOTIFICATIONS",
  PERMISSIONS: "PERMISSIONS",
  PLANS: "PLANS",
  PROFILE: "PROFILE",
  ROLES: "ROLES",
  SETTINGS: "SETTINGS",
  SERVICES: "SERVICES",
  USERS: "USERS",
  TESTS: "TESTS",
  UPLOADS: "UPLOADS",
});
